[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mycord"
version = "1.0.9"
authors = [
    { name = "amri4", email = "amri.supreme123@gmail.com" }
]
description = "A minimalist Discord bot framework that communicates directly with Discord Gateway and REST."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "discord.py>=2.0.0",
    "python-dotenv>=1.0.0"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mycord*"]

